services:
  - type: web
    name: semantic-search-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/out

  - type: web
    name: semantic-search-fastapi
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: uvicorn DL_model:app --host 0.0.0.0 --port $PORT
    workingDir: backend
